<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Readme.md" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Readme.md" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Nullable" PrivateAssets="all" />
    <PackageReference Include="IsExternalInit" PrivateAssets="all" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Reactive.Testing" />
    <PackageReference Include="RavenDB.Client" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Sinks.PeriodicBatching" />
    <PackageReference Include="Serilog.Exceptions" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\HomeCenter.Actors\HomeCenter.Actors.csproj" />
    <ProjectReference Include="..\HomeCenter.Configuration\HomeCenter.Configuration.csproj" />
    <ProjectReference Include="..\HomeCenter.EventAggregator\HomeCenter.EventAggregator.csproj" />
    <ProjectReference Include="..\HomeCenter.Storage.RavenDB\HomeCenter.Storage.RavenDB.csproj" />
  </ItemGroup>
</Project>