//--------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//--------------------------------------------------------------------------------------------------
using HomeCenter.Abstractions;

namespace HomeCenter.SourceGenerators.Tests
{
    [GeneratedCode]
    public partial class MessageGenerator
    {
        public async System.Threading.Tasks.Task<Event> PublishEvent(ActorMessage source, ActorMessage destination, IMessageBroker messageBroker, EventAggregator.RoutingFilter routingFilter)
        {
            if (destination.Type == "TestEvent")
            {
                var @event = new HomeCenter.SourceGenerators.Tests.TestEvent();
                @event.SetProperties(source);
                @event.SetProperties(destination);
                await messageBroker.Publish(@event, routingFilter);
                return @event;
            }
            else if (destination.Type == "TestEvent")
            {
                var @event = new HomeCenter.SourceGenerators.Tests.TestEvent();
                @event.SetProperties(source);
                @event.SetProperties(destination);
                await messageBroker.Publish(@event, routingFilter);
                return @event;
            }
            else if (destination.Type == "TestEvent2")
            {
                var @event = new HomeCenter.SourceGenerators.Tests.TestEvent2();
                @event.SetProperties(source);
                @event.SetProperties(destination);
                await messageBroker.Publish(@event, routingFilter);
                return @event;
            }
            else if (destination.Type == "TestEvent2")
            {
                var @event = new HomeCenter.SourceGenerators.Tests.TestEvent2();
                @event.SetProperties(source);
                @event.SetProperties(destination);
                await messageBroker.Publish(@event, routingFilter);
                return @event;
            }
            else if (destination.Type == "DipswitchEvent")
            {
                var @event = new HomeCenter.Messages.Events.Device.DipswitchEvent();
                @event.SetProperties(source);
                @event.SetProperties(destination);
                await messageBroker.Publish(@event, routingFilter);
                return @event;
            }
            else if (destination.Type == "InfraredEvent")
            {
                var @event = new HomeCenter.Messages.Events.Device.InfraredEvent();
                @event.SetProperties(source);
                @event.SetProperties(destination);
                await messageBroker.Publish(@event, routingFilter);
                return @event;
            }
            else if (destination.Type == "MotionEvent")
            {
                var @event = new HomeCenter.Messages.Events.Device.MotionEvent();
                @event.SetProperties(source);
                @event.SetProperties(destination);
                await messageBroker.Publish(@event, routingFilter);
                return @event;
            }
            else if (destination.Type == "PinValueChangedEvent")
            {
                var @event = new HomeCenter.Messages.Events.Device.PinValueChangedEvent();
                @event.SetProperties(source);
                @event.SetProperties(destination);
                await messageBroker.Publish(@event, routingFilter);
                return @event;
            }
            else if (destination.Type == "PowerStateChangeEvent")
            {
                var @event = new HomeCenter.Messages.Events.Device.PowerStateChangeEvent();
                @event.SetProperties(source);
                @event.SetProperties(destination);
                await messageBroker.Publish(@event, routingFilter);
                return @event;
            }
            else if (destination.Type == "PropertyChangedEvent")
            {
                var @event = new HomeCenter.Messages.Events.Device.PropertyChangedEvent();
                @event.SetProperties(source);
                @event.SetProperties(destination);
                await messageBroker.Publish(@event, routingFilter);
                return @event;
            }
            else if (destination.Type == "SerialResultEvent")
            {
                var @event = new HomeCenter.Messages.Events.Device.SerialResultEvent();
                @event.SetProperties(source);
                @event.SetProperties(destination);
                await messageBroker.Publish(@event, routingFilter);
                return @event;
            }
            else if (destination.Type == "ComponentStartedEvent")
            {
                var @event = new HomeCenter.Messages.Events.Service.ComponentStartedEvent();
                @event.SetProperties(source);
                @event.SetProperties(destination);
                await messageBroker.Publish(@event, routingFilter);
                return @event;
            }
            else if (destination.Type == "SystemStartedEvent")
            {
                var @event = new HomeCenter.Messages.Events.Service.SystemStartedEvent();
                @event.SetProperties(source);
                @event.SetProperties(destination);
                await messageBroker.Publish(@event, routingFilter);
                return @event;
            }

            var ev = new Event();
            ev.SetProperties(source);
            ev.SetProperties(destination);
            await messageBroker.Publish(ev, routingFilter);
            return ev;
        }

        public Command CreateCommand(string message)
        {
            if (message == "TestCommand")
            {
                return new HomeCenter.SourceGenerators.Tests.TestCommand();
            }
            else if (message == "TestCommand")
            {
                return new HomeCenter.SourceGenerators.Tests.TestCommand();
            }
            else if (message == "Test2Command")
            {
                return new HomeCenter.SourceGenerators.Tests.Test2Command();
            }
            else if (message == "Test2Command")
            {
                return new HomeCenter.SourceGenerators.Tests.Test2Command();
            }
            else if (message == "AdjustPowerLevelCommand")
            {
                return new HomeCenter.Messages.Commands.Device.AdjustPowerLevelCommand();
            }
            else if (message == "CalibrateCommand")
            {
                return new HomeCenter.Messages.Commands.Device.CalibrateCommand();
            }
            else if (message == "InputSetCommand")
            {
                return new HomeCenter.Messages.Commands.Device.InputSetCommand();
            }
            else if (message == "ModeSetCommand")
            {
                return new HomeCenter.Messages.Commands.Device.ModeSetCommand();
            }
            else if (message == "MuteCommand")
            {
                return new HomeCenter.Messages.Commands.Device.MuteCommand();
            }
            else if (message == "PlayCommand")
            {
                return new HomeCenter.Messages.Commands.Device.PlayCommand();
            }
            else if (message == "RefreshCommand")
            {
                return new HomeCenter.Messages.Commands.Device.RefreshCommand();
            }
            else if (message == "RefreshLightCommand")
            {
                return new HomeCenter.Messages.Commands.Device.RefreshLightCommand();
            }
            else if (message == "SetPowerLevelCommand")
            {
                return new HomeCenter.Messages.Commands.Device.SetPowerLevelCommand();
            }
            else if (message == "StopCommand")
            {
                return new HomeCenter.Messages.Commands.Device.StopCommand();
            }
            else if (message == "SwitchPowerStateCommand")
            {
                return new HomeCenter.Messages.Commands.Device.SwitchPowerStateCommand();
            }
            else if (message == "TurnOffCommand")
            {
                return new HomeCenter.Messages.Commands.Device.TurnOffCommand();
            }
            else if (message == "TurnOnCommand")
            {
                return new HomeCenter.Messages.Commands.Device.TurnOnCommand();
            }
            else if (message == "UnmuteCommand")
            {
                return new HomeCenter.Messages.Commands.Device.UnmuteCommand();
            }
            else if (message == "VolumeDownCommand")
            {
                return new HomeCenter.Messages.Commands.Device.VolumeDownCommand();
            }
            else if (message == "VolumeSetCommand")
            {
                return new HomeCenter.Messages.Commands.Device.VolumeSetCommand();
            }
            else if (message == "VolumeUpCommand")
            {
                return new HomeCenter.Messages.Commands.Device.VolumeUpCommand();
            }
            else if (message == "SendCodeCommand")
            {
                return new HomeCenter.Messages.Commands.Device.SendCodeCommand();
            }
            else if (message == "HttpCommand")
            {
                return new HomeCenter.Messages.Commands.Service.HttpCommand();
            }
            else if (message == "I2cCommand")
            {
                return new HomeCenter.Messages.Commands.Service.I2cCommand();
            }
            else if (message == "StartSystemCommand")
            {
                return new HomeCenter.Messages.Commands.Service.StartSystemCommand();
            }
            else if (message == "TcpCommand")
            {
                return new HomeCenter.Messages.Commands.Service.TcpCommand();
            }
            else if (message == "UdpCommand")
            {
                return new HomeCenter.Messages.Commands.Service.UdpCommand();
            }
            else if (message == "WakeOnLanCommand")
            {
                return new HomeCenter.Messages.Commands.Service.WakeOnLanCommand();
            }
            else if (message == "RegisterPinChangedCommand")
            {
                return new HomeCenter.Messages.Queries.Service.RegisterPinChangedCommand();
            }
            else if (message == "RegisterSerialCommand")
            {
                return new HomeCenter.Messages.Queries.Service.RegisterSerialCommand();
            }

            return new Command();
        }
    }
}