<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Reactive.Interfaces" />
    <PackageReference Include="Light.GuardClauses" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HomeCenter.EventAggregator.Abstractions\HomeCenter.EventAggregator.Abstractions.csproj" />
    <ProjectReference Include="..\HomeCenter.Extensions\HomeCenter.Extensions.csproj" />
  </ItemGroup>
</Project>